### ISSUE TITLE
dash support

### ISSUE THREAD

**Issue by DustinChaloupka** [jenv/jenv#360]
After #355 `dash` as the shell no longer works. At least for our scenario, we do not care about having auto completion or any of the other hooks and things added from `jenv init -`.

I could not find any explicit mention of what this project does plan to support for shells, so this is a request to support `dash` at the very least in the case of `jenv init -` where it does not add a completion `source` and does not use `typeset`.

**Comment by marquiswang** [comment]
Can you check after #358 was merged? That partially reverted the changes from #355. Otherwise I wouldn't mind adding explicit `sh` support.

**Comment by DustinChaloupka** [comment]
Double checked that it still does not work. It's the default addition [here](https://github.com/marquiswang/jenv/blob/b13e366d7a97d8677aa32ac01b1158fcd13f0d16/libexec/jenv-init#L150) where `typeset` is not available in `/bin/sh` where it currently fails.

**Comment by marquiswang** [comment]
Out of curiosity, what sh version are you using? On my machine sh v3.2 comes with typeset.

Anyways, I pushed a commit that avoids calling `typeset` if it isn't available. Can you give that a try?

**Comment by DustinChaloupka** [comment]
I should've looked closer first at what `/bin/sh` was linked to to not be confusing, which in this case was `dash`, and the version is `0.5.10.2-6`. The change to check for `typeset` in the commit does not work with the `-e` shell flag, but we are able to unset that for what we are doing and ignore the `typeset not found` error still present.
